title: gauk.as - Jekyll URL Shortener
description: URL Shortener hosted on GitHub Pages
# logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug

plugins:
  - jekyll-redirect-from

# repository: gaukas/gauk.as
